/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kata.base

import io.kotest.core.spec.style.WordSpec
import io.kotest.matchers.shouldNotBe

class AppTest: WordSpec({
    "testAppHasAGreeting" should {
        val classUnderTest = App()
        classUnderTest.greeting shouldNotBe null
    }
})
