/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kata.base

import io.kotest.core.spec.style.WordSpec
import io.kotest.matchers.shouldBe
import io.kotest.matchers.shouldNotBe
import org.junit.jupiter.api.Assertions.assertEquals
import kotlin.random.Random

class StockTest: WordSpec({
    "combine" should {
        "50" {
            val result = Stock(20) + Stock(30)
            result shouldBe Stock(50)
        }
        "30" {
            val result = Stock(20) + Stock(10)
            result shouldBe Stock(30)
        }
        "Neutral" {
            val result = forAnyStock();
            result + Stock.NEUTRAL shouldBe result
            Stock.NEUTRAL + result shouldBe result
        }

        "associative" {
            val a = forAnyStock()
            val b = forAnyStock()
            val c = forAnyStock()

            a + b + c shouldBe b + c + a
        }
    }
})

fun forAnyStock() = Stock(Random.nextInt())
