/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kata.base


import io.kotest.core.spec.style.WordSpec
import io.kotest.matchers.shouldBe
import io.kotest.matchers.shouldNotBe
import io.kotest.property.Arb
import io.kotest.property.arbitrary.arbitrary
import io.kotest.property.arbitrary.int
import io.kotest.property.arbitrary.next
import io.kotest.property.forAll
import org.junit.jupiter.api.Assertions.assertEquals
import kotlin.random.Random

class StockTest : WordSpec({
    "combine" should {
        "50" {
            val result = Stock(20) + Stock(30)
            result shouldBe Stock(50)
        }
        "30" {
            val result = Stock(20) + Stock(10)
            result shouldBe Stock(30)
        }
        "Neutral" {
            val result = forAnyStock();
            result + Stock.NEUTRAL shouldBe result
            Stock.NEUTRAL + result shouldBe result
        }

        "associative" {
            val a = forAnyStock()
            val b = forAnyStock()
            val c = forAnyStock()

            a + b + c shouldBe b + c + a
        }
        "pbt" {
            forAll(anyStock, anyStock) { a, b ->
                a + b == Stock(a.value + b.value)
            }
        }
    }
})

fun forAnyStock() = Stock(Random.nextInt())

val anyStock = arbitrary { rs ->
    val value = Arb.int(21, 150).next(rs)
    Stock(value)
}
